apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rlabdev-service-api
  description: The Service API Description
  annotations:
    tags: "backend, service"
spec:
  type: service
  lifecycle: experimental
  owner: rca0
  docs:
    overview: docs/index.md
  providesApis:
    - "rlabdev-service-api"
  visibility: public
  relations:
    - type: uses-resource
      target: rds-postgresql
    - type: uses-resource
      target: aws-sqs-queue

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rds-postgresql
  description: RDS PostgreSQL Database
  annotations:
    type: database
    provider: aws
spec:
  type: aws:rds:postgresql
  lifecycle: development
  owner: infrastructure-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-sqs-queue
  description: AWS SQS Queue
  annotations:
    type: messaging
    provider: aws
spec:
  type: aws:sqs
  lifecycle: development
  owner: infrastructure-team
