apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rlabdev
  description: The Service Description
  annotations:
    tags: "backend, service"
spec:
  type: service
  lifecycle: experimental
  owner: rca0
  providesApis:
    - "rlabdev-service-api"
  visibility: public  
  relations:
    - type: uses-service
      target: rlabdev-worker
    - type: uses-resource
      target: rds-postgresql
    - type: uses-resource
      target: aws-sqs-queue
    - type: uses-resource
      target: kafka
    - type: uses-resource
      target: redis-cache
    - type: belongs-to
      target: group:default/rca0
    - type: uses-api
      target: api:default/rlabdev-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rds-postgresql
  description: RDS PostgreSQL Database
  annotations:
    type: database
    provider: aws
spec:
  type: aws:rds:postgresql
  lifecycle: development
  owner: infrastructure-team
  relations:
    - type: uses-api
      target: api:default/rlabdev-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-sqs-queue
  description: AWS SQS Queue
  annotations:
    type: messaging
    provider: aws
    topicOrQueueName: sqs-queue-name-1
spec:
  type: aws:sqs
  lifecycle: development
  owner: infrastructure-team
  relations:
    - type: uses-api
      target: api:default/rlabdev-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kafka
  description: Kafka
  annotations:
    type: messaging
    topicOrQueueName: kafka-topic-name-1
spec:
  type: messaging:kafka
  lifecycle: development
  owner: infrastructure-team
  relations:
    - type: uses-api
      target: api:default/rlabdev-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: redis-cache
  description: Redis Cache
  annotations:
    type: cache
spec:
  type: caching:redis
  lifecycle: development
  owner: infrastructure-team
  relations:
    - type: uses-api
      target: api:default/rlabdev-service-api

---
---
apiVersion: backstage.io/v1alpha1
kind: Api
metadata:
  name: rlabdev-service-api
  description: API for the rlabdev service
  annotations:
    visibility: public
spec:
  openapiDefinition: # Add your OpenAPI definition here
    info:
      title: rlabdev Service API
      version: 1.0.0
    paths:
      /example:
        get:
          summary: Get example data
          responses:
            '200':
              description: OK
