apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rlabdev-service-api
spec:
  type: grpc
  lifecycle: experimental
  owner: rca0
  system: rlabdev-service-api
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
