apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: rlabdev-service
spec:
  owner: rca0

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rlabdev-service-api
  description: The Service API Description
  annotations:
    tags: "backend, service"
spec:
  type: service
  lifecycle: experimental
  owner: rca0
  docs:
    overview: docs/index.md
  providesApis:
    - "rlabdev-service-api"
  visibility: public
