apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rca0
spec:
  type: team
  parent: default

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rlabdev-service-api
  description: API for rlabdev service
spec:
  type: openapi
  lifecycle: production
  owner: rca0
  definition: https://rlabdev.com/docs/openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Catalog
metadata:
  name: default
spec:
  owner: backstage
  description: Default catalog for Backstage
  entries:
    - metadata:
        type: group
        name: rca0
        description: Team RCA0
    - metadata:
        type: api
        name: rlabdev-service-api
        description: API for rlabdev service

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rlabdev-service-api
  description: The Service API Description
  annotations:
    tags: "backend, service"
spec:
  type: service
  lifecycle: experimental
  owner: rca0
  docs:
    overview: docs/index.md
  providesApis:
    - "rlabdev-service-api"
  visibility: public
  relations:
    - type: uses-resource
      target: rds-postgresql
    - type: uses-resource
      target: aws-sqs-queue

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rds-postgresql
  description: RDS PostgreSQL Database
  annotations:
    type: database
    provider: aws
spec:
  type: aws:rds:postgresql
  lifecycle: development
  owner: infrastructure-team

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aws-sqs-queue
  description: AWS SQS Queue
  annotations:
    type: messaging
    provider: aws
spec:
  type: aws:sqs
  lifecycle: development
  owner: infrastructure-team
